### PR TITLE
Changed song selection screen

### PR DESCRIPTION
**Pull request by LoveEevee**
- Gamepad or keyboard can be used in every menu without needing a mouse
- Animation when selecting a song and difficulty is missing right now
- Removed endclear animation

### CODE REVIEW

**Comment by bui** [comment]
Thank you, a few things I noticed about song select:

* Song select BGM is missing, and background isn't scrolling?
* "Tutorial" should be the initial selection on startup
* Navigating songs with keyboard is way too slow. Is it possible to speed it up (similar speed to AC)?
* "Back" isn't really needed outside of folders
* Holding down a navigation key on `熱情のスペクトラム` should stop the preview, but it keeps playing. Only seems to happen for this song?
* Small kana (eg. the `ィ` in `黒ビィんの翼`) is slightly to the right in song titles

I'll post any more issues I come across.

**Comment by bui** [comment]
Keyboard can't be used in result screen (?)

**Comment by bui** [comment]
* If keyboard is used to select a difficulty, mouse doesn't change active selection and can be hovered over "Back" to show two 1P icons
* Similar issue in pause menu, where Continue is highlighted by default, but mouse can be hovered to show two active choices
* Pause menu buttons have outlines (I don't think they did before)

**Comment by LoveEevee** [comment]
- Song select BGM is missing because I felt it was better without it
- The initial selection is the last song that was played, tutorial will still show for new players
- I tried to modify the song selection to be faster, but could not get it to work, will look into that in a future PR
- There are no folders currently and it looks weird without any buttons that would separate the song list from "random song" and "tutorial" buttons
- Fixed preview getting stuck for the first song
- Small kanas are at the right intentionally, they are supposed to be at the right in vertical writing
- Ura oni is not implemented in `app.py` yet either
- Added Auto and P2 for gamepad, hold down X or Y and start the song
- Added keyboard and gamepad support to the scoresheet
- Fixed double 1P icons
- Fixed double highlighted entries in the pause menu
- Fixed outlines in the pause menu

**Comment by bui** [comment]
>Song select BGM is missing because I felt it was better without it

Perhaps you feel that way, but it is still a part of the game we are trying to simulate. Please undo this change

>The initial selection is the last song that was played, tutorial will still show for new players

For new players, the first song is shown. This should be changed to tutorial, as it is in AC. But continue to show the tutorial automatically anyway since it may be hard to locate it to new players, at least until english localisation

**Comment by bui** [comment]
Don keys can't be used to confirm pause mention selection, only enter works

**Comment by bui** [comment]
songsel BGM should not play when moving between songs

**Pull request merged**
