### PR TITLE
Add Rainbow crown

### PR DESCRIPTION
**Pull request by purerosefallen**

### CODE REVIEW

**Comment by purerosefallen** [comment]
Rainbow cron is the crown introduced in AC16 obtained when all-perfect score.
image

The crown may not be well drawn, and the sound is to be added.

**Comment by purerosefallen** [comment]
I have also written a tool migrating all old scores with all-perfect score to the rainbow crown, but written in Typescript instead of Python...
If needed I may post it here.

**Comment by HatsuneMiku831** [comment]
初めてコメントします。
アイドルマスターのキラメキラリの裏譜面が給付面ではありません。修正の方よろしくお願いします

**Comment by HatsuneMiku831** [comment]
キラメキラリの裏譜面（旧譜面）が新譜面と同じなので修正お願いします

**Comment by HatsuneMiku831** [comment]
なんでコメント消えるの

**Pull request closed without merging**
