### PR TITLE
starting combo text from 3 combos

### PR DESCRIPTION
**Pull request by purerosefallen**
This matches the AC's behavior.
Reference: https://www.youtube.com/watch?v=WKIEbj6n9IE

### CODE REVIEW

**Comment by bui** [comment]
This behaviour only occurs starting from Yellow Ver., but taiko-web doesn't follow any specific game's style 100% of the way, although you could argue the left part of the lane is more reminiscent of Red Ver.

It's a minor change but I don't feel the need to merge it right away; I'd rather leave it open for discussion as there could be some people who prefer it to stay at 10 for one reason or another.

**Comment by purerosefallen** [comment]
How about making it a setting..?
I feel 3 combo is better for playing because sometimes we may be unaware of missing any notes before the 10th note.

**Comment by LoveEevee** [comment]
The combo number on the newest arcade does not start at 3
https://www.youtube.com/watch?v=Ga_wchCRrtU

**Comment by bui** [comment]
starts at 5 for easy and normal https://www.youtube.com/watch?v=zsuV4fr8suo

**Pull request closed without merging**
