### PR TITLE
Add global offset

### PR DESCRIPTION
**Pull request by LoveEevee**
Adds new settings for controlling the note offset while playing. It can be either an actual offset (it is called "Audio Latency" in the settings) or just the visual offset ("Video Latency").
With higher audio latency it means you have to press the button sooner than what you hear, similarly with higher video latency it is sooner than what you see. By offsetting these events the game would play better, however, the sound effect of you hitting the drum would still play at the wrong time, the code cannot anticipate you to hit the drum in the future so to work around this issue a new option that disables drum sounds is also included.
These settings could be set through trial and error but it would be better to get the correct values through the automated latency calibration, where you can hit the drum as you hear sounds or see a blinking animation. I tried making one by measuring latency from user input, adding all the latency up, and dividing, but that gives unreliable results. I hope someone suggests to me what I should be doing during the calibration to get better results, as I cannot figure what to do on my own.

### CODE REVIEW

**Comment by purerosefallen** [comment]
What is calibration.wav? that file is blank.

**Comment by LoveEevee** [comment]
@purerosefallen it is not blank, just a really short sound effect, it plays on loop during the audio calibration

**Comment by BlueJYT** [comment]
Thank you so much for this coming update. This is something that will definitely help a lot of people playing this.

**Comment by BlueJYT** [comment]
Yaay! This new update is amazing! I love playing with this. Thanks everybody!

**Pull request merged**
