### PR TITLE
Translation Enhancements (zh-TW/zh-CN)

### PR DESCRIPTION
**Pull request by bckps7336**
- Fixed incomplete translations from CN to TW
- Changed word usages to existing translations

### CODE REVIEW

**Comment by bui** [comment]
Thank you!

**Comment by bui** [comment]
@bckps7336 The string "遊戲音樂" (zh-TW) for Game Music is how it is displayed in Taiko no Tatsujin for Switch. Is there a reason you replaced it with "電子遊戲音樂" or would it be OK for me to revert that string?

**Comment by bckps7336** [comment]
I referenced the translation from here:
http://zh.taiko.wikia.com/wiki/電子遊戲音樂

I think you can revert that since you got that from the official source.

**Comment by bui** [comment]
👍

**Pull request merged**
